### ISSUE TITLE
Trouble importing in py3.x

### ISSUE THREAD

**Issue by IanEisenberg** [kylessmith/dynamicTreeCut#3]
I was having trouble importing this package in py3.x. Kept getting a `ImportError: No module named 'df_apply'`

I corrected this by changing the imports in dynamicTreeCut.py to `import dynamicTreeCut.df_apply`. Not sure why it was failing, as it seems like a fine pip package though...

**Comment by mpschr** [comment]
yup same here

**Comment by ermiaswalelgne** [comment]
Also `'ImportError: No module named 'R_func'` error is fixed by replacing` from R_func import *` with `from dynamicTreeCut.R_func import *.`
